version: '3.9'

services:
  api:
    build: .
    container_name: vulntrack-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY}
      - BRAVE_SEARCH_BASE_URL=${BRAVE_SEARCH_BASE_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  worker:
    build: .
    container_name: vulntrack-worker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: ["celery", "-A", "app.worker", "worker", "--loglevel=info", "--pool=solo"]

  flower:
    build: .
    container_name: vulntrack-flower
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    ports:
      - "5555:5555"
    command: ["celery", "-A", "app.worker", "flower", "--port=5555", "--pool=solo"]

  redis:
    image: redis:7.2-alpine
    container_name: vulntrack-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
